### ISSUE TITLE
./configure -> Invalid configuration `x86_64-unknown-linux-gnu'

### ISSUE THREAD

**Issue by livibetter** [rwestlund/freesweep#1]
This is the first time I saw this error:

```
% ./configure
checking build system type... Invalid configuration `x86_64-unknown-linux-gnu': machine `x86_64-unknown' not recognized
configure: error: /bin/sh ./config.sub x86_64-unknown-linux-gnu failed.
```

I tried `autoreconf` and got these warning, don't think it's related and didn't work, still got the same message above afterwards:

```
% autoreconf -i
aclocal-1.15: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoheader-2.69: WARNING: Using auxiliary files such as `acconfig.h', `config.h.bot'
autoheader-2.69: WARNING: and `config.h.top', to define templates for `config.h.in'
autoheader-2.69: WARNING: is deprecated and discouraged.
autoheader-2.69:
autoheader-2.69: WARNING: Using the third argument of `AC_DEFINE' and
autoheader-2.69: WARNING: `AC_DEFINE_UNQUOTED' allows one to define a template without
autoheader-2.69: WARNING: `acconfig.h':
autoheader-2.69:
autoheader-2.69: WARNING:   AC_DEFINE([NEED_FUNC_MAIN], 1,
autoheader-2.69:                [Define if a function `main' is needed.])
autoheader-2.69:
autoheader-2.69: WARNING: More sophisticated templates can also be produced, see the
autoheader-2.69: WARNING: documentation.
```

I found a [solution][]:

```
% cp /usr/share/libtool/build-aux/config.{guess,sub} .
```

[solution]: http://www.noah.org/wiki/Jpegsrc_64

It worked. After that, I checked the `config.guess` and `config.sub`, they were last copyright 1999. And I just realized freesweep was from that time, too.

Time to update the last century build tool?

**Comment by hananeam1991** [comment]
hanane@hanane-HP-Pavilion-g6-Notebook-PC:~/Bureau/PACK-ALIZE/alize-core-master$ make
Making all in src
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master/src »
rm -f libalize.a
ar cru libalize.a alizeString.o AudioFileReader.o AudioFrame.o AudioInputStream.o AutoDestructor.o CmdLine.o Config.o ConfigChecker.o ConfigFileReaderAbstract.o ConfigFileReaderRaw.o ConfigFileReaderXml.o ConfigFileWriter.o Distrib.o DistribGD.o DistribGF.o DistribRefVector.o DoubleSquareMatrix.o Exception.o Feature.o FeatureFileList.o FeatureFileReader.o FeatureFileReaderAbstract.o FeatureFileReaderHTK.o FeatureFileReaderRaw.o FeatureFileReaderSPro3.o FeatureFileReaderSPro4.o FeatureFileReaderSingle.o FeatureFileWriter.o FeatureFlags.o FeatureInputStream.o FeatureInputStreamModifier.o FeatureMultipleFileReader.o FeatureServer.o FileReader.o FileWriter.o FrameAcc.o FrameAccGD.o FrameAccGF.o Histo.o LKVector.o Label.o LabelFileReader.o LabelServer.o LabelSet.o Mixture.o MixtureDict.o MixtureFileReader.o MixtureFileReaderAbstract.o MixtureFileReaderAmiral.o MixtureFileReaderRaw.o MixtureFileReaderXml.o MixtureFileWriter.o MixtureGD.o MixtureGDStat.o MixtureGF.o MixtureGFStat.o MixtureServer.o MixtureServerFileReader.o MixtureServerFileReaderAbstract.o MixtureServerFileReaderRaw.o MixtureServerFileReaderXml.o MixtureServerFileWriter.o MixtureStat.o Object.o Seg.o SegAbstract.o SegCluster.o SegServer.o SegServerFileReaderAbstract.o SegServerFileReaderRaw.o SegServerFileWriter.o StatServer.o ULongVector.o ViterbiAccum.o XLine.o XList.o XListFileReader.o XmlParser.o 
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
ranlib libalize.a
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master/src »
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master »
make[1]: rien à faire pour « all-am ».
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master »
mkdir -p lib ; mv src/libalize.a lib/libalize_Linux_x86_64.a
i have this error please help me to have a solution i want to install alize but when i run make i have this error

**Comment by kapilgarg1996** [comment]
@livibetter I faced this issue while installing cgicc and the same solution worked. But i didn't understand why old files were causing this issue ?
