### ISSUE TITLE
Infinite loop when creating too many mines

### ISSUE THREAD

**Issue by apoleon** [rwestlund/freesweep#4]
This is Debian bug https://bugs.debian.org/249896. 

freesweep enters an infinite loop when placing mines if the user's
configuration has it creating more than (boardsize - 9) mines.  This is
caused by game.c:510 not allowing mines to be created within a 3x3 block
at the centre of the field, while the initial configuration allows for
more than (boardsize - 9) mines to be created.  This patch makes a board
size of 3x3 invalid because no mines can be placed and lowers the 
maximum allowable number of mines on a board to (boardsize - 9).

Patch can be found here:
https://salsa.debian.org/games-team/freesweep/blob/master/debian/patches/do-not-create-too-many-mines

**Comment by digitalcombine** [comment]
I do believe this is fixed now with the smallest board size limited to 10x10 and the mine percentages being between 10% - 90% of the game boards.
